
resources:
  - name: timer.time
    type: time
    check_every: 1m
    source:
      interval: 5m

  - name: pipeline-test.git
    type: git
    check_every: 1m
    source:
      uri: git@github.com:iAmoric/pipeline-test.git
      branch: ((branch))
      private_key: ((github_ssh_key))


jobs:

  - name: pipeline-test
    plan:
      - get: timer.time
        trigger: true
      - get: pipeline-test.git
        trigger: false
      - task: timer
        file: pipeline-test.git/ci/tasks/task.yml
