platform: linux
image_resource:
  type: registry-image
  source:
    repository: busybox
inputs:
  - name: pipeline-test.git


run:
  path: /bin/sh
  args:
  - -c
  - |
    set -o errexit
    echo "Hello world"
    cd pipeline-test.git
    ls
    cat .git/ref
