platform: linux
image_resource:
  type: registry-image
  source:
    repository: busybox
inputs:
  - name: timer.time
  - name: pipeline-test.git


run:
  path: /bin/sh
  args:
  - -c
  - |
    cd pipeline-test.git
    date
    cat .git/ref
