platform: linux
image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.8
inputs:
  - name: pipeline-test.git


run:
  path: /bin/sh
  args:
  - -c
  - |
    set -o errexit
    ls
    echo "Hello world"
